package war;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class WarDeal {
	protected static void handConstructor(WarPlayer player, WarPlayer computer) {
		List<WarCards> z = new ArrayList<>();
		WarCards one = new WarCards("2H", 2);
		WarCards two = new WarCards("2S", 2);
		WarCards three = new WarCards("2D", 2);
		WarCards four = new WarCards("2C", 2);
		WarCards five = new WarCards("3H", 3);
		WarCards six = new WarCards("3S", 3);
		WarCards seven = new WarCards("3D", 3);
		WarCards eight = new WarCards("3C", 3);
		WarCards nine = new WarCards("4H", 4);
		WarCards ten = new WarCards("4S", 4);
		WarCards eleven = new WarCards("4D", 4);
		WarCards twelve = new WarCards("4C", 4);
		WarCards thirteen = new WarCards("5H", 5);
		WarCards fourteen = new WarCards("5S", 5);
		WarCards fifteen = new WarCards("5D", 5);
		WarCards sixteen = new WarCards("5C", 5);
		WarCards seventeen = new WarCards("6H", 6);
		WarCards eighteen = new WarCards("6S", 6);
		WarCards nineteen = new WarCards("6D", 6);
		WarCards twenty = new WarCards("6C", 6);
		WarCards twentyone = new WarCards("7H", 7);
		WarCards twentytwo = new WarCards("7S", 7);
		WarCards twentythree = new WarCards("7D", 7);
		WarCards twentyfour = new WarCards("7C", 7);
		WarCards twentyfive = new WarCards("8H", 8);
		WarCards twentysix = new WarCards("8S", 8);
		WarCards twentyseven = new WarCards("8D", 8);
		WarCards twentyeight = new WarCards("8C", 8);
		WarCards twentynine = new WarCards("9H", 9);
		WarCards thirty = new WarCards("9S", 9);
		WarCards thirtyone = new WarCards("9D", 9);
		WarCards thirtytwo = new WarCards("9C", 9);
		WarCards thirtythree = new WarCards("TH", 10);
		WarCards thirtyfour = new WarCards("TS", 10);
		WarCards thirtyfive = new WarCards("TD", 10);
		WarCards thirtysix = new WarCards("TC", 10);
		WarCards thirtyseven = new WarCards("JH", 11);
		WarCards thirtyeight = new WarCards("JS", 11);
		WarCards thirtynine = new WarCards("JD", 11);
		WarCards forty = new WarCards("JC", 11);
		WarCards fortyone = new WarCards("QH", 12);
		WarCards fortytwo = new WarCards("QS", 12);
		WarCards fortythree = new WarCards("QD", 12);
		WarCards fortyfour = new WarCards("QC", 12);
		WarCards fortyfive = new WarCards("KH", 13);
		WarCards fortysix = new WarCards("KS", 13);
		WarCards fortyseven = new WarCards("KD", 13);
		WarCards fortyeight = new WarCards("KC", 13);
		WarCards fortynine = new WarCards("AH", 14);
		WarCards fifty = new WarCards("AS", 14);
		WarCards fiftyone = new WarCards("AD", 14);
		WarCards fiftytwo = new WarCards("AC", 14);
		z.add(one);
		z.add(two);
		z.add(three);
		z.add(four);
		z.add(five);
		z.add(six);
		z.add(seven);
		z.add(eight);
		z.add(nine);
		z.add(ten);
		z.add(eleven);
		z.add(twelve);
		z.add(thirteen);
		z.add(fourteen);
		z.add(fifteen);
		z.add(sixteen);
		z.add(seventeen);
		z.add(eighteen);
		z.add(nineteen);
		z.add(twenty);
		z.add(twentyone);
		z.add(twentytwo);
		z.add(twentythree);
		z.add(twentyfour);
		z.add(twentyfive);
		z.add(twentysix);
		z.add(twentyseven);
		z.add(twentysix);
		z.add(twentyseven);
		z.add(twentyeight);
		z.add(twentynine);
		z.add(thirty);
		z.add(thirtyone);
		z.add(thirtytwo);
		z.add(thirtythree);
		z.add(thirtyfour);
		z.add(thirtyfive);
		z.add(thirtysix);
		z.add(thirtyseven);
		z.add(thirtyeight);
		z.add(thirtynine);
		z.add(forty);
		z.add(fortyone);
		z.add(fortytwo);
		z.add(fortythree);
		z.add(fortyfour);
		z.add(fortyfive);
		z.add(fortysix);
		z.add(fortyseven);
		z.add(fortyeight);
		z.add(fortynine);
		z.add(fifty);
		z.add(fiftyone);
		z.add(fiftytwo);
		
		
		Collections.shuffle(z);
		
		for(int i = 0; i <= 25; i++) {
			player.deck.add(z.get(0));
			z.remove(0);
			computer.deck.add(z.get(0));
			z.remove(0);
		}
	}
}
